---
- hosts: web
  gather_facts: false
  become: true
  tasks:
    - name: shell git clone
      ansible.builtin.shell:
        cmd: "git clone {{git_repo}} {{repo_dir}}"
      args:
        chdir: /tmp

    - name: Change permission of start.sh
      ansible.builtin.file:
        path: "{{ repo_dir }}{{item}}"
        mode: '0755'
        owner: root
        group: root
      loop:
        - "{{start_path}}"
        - "{{stop_path}}"

    - name: Start the application
      ansible.builtin.shell: "{{repo_dir}}{{start_path}}"
      args:
        chdir: "{{ repo_dir }}"
      register: start_output

    - name: Display the output of start.sh
      ansible.builtin.debug:
        msg: "{{ start_output.stdout }}"

    - name: Stop the application
      ansible.builtin.shell: "{{repo_dir}}{{stop_path}}"
      args:
        chdir: "{{ repo_dir }}"
      register: stop_output

    - name: Display the output of stop.sh
      ansible.builtin.debug:
        msg: "{{ stop_output.stdout }}"

    - name: Remove the application directory
      ansible.builtin.shell:
        cmd: "rm -rf {{ repo_dir }}"