---
- hosts: web
  gather_facts: false
  become: true
  tasks:
    - name: shell git clone
      ansible.builtin.shell:
        cmd: "git clone https://github.com/navneet-rathi/git-sample.git"
      args:
        chdir: /tmp

    - name: Change permission of start.sh
      ansible.builtin.file:
        path: "{{ exercise_dir }}/start.sh"
        mode: '0755'
        owner: root
        group: root

    - name: Start the application
      ansible.builtin.shell: ./start.sh
      args:
        chdir: "{{ exercise_dir }}"

    - name: Stop the application
      ansible.builtin.shell: ./stop.sh
      args:
        chdir: "{{ exercise_dir }}"
