---
- hosts: web
  gather_facts: false
  tasks:
    - name: Print the playbook directory
      ansible.builtin.shell:
        shell: git clone https://github.com/navneet-rathi/git-sample.git 
        agrs:
          chdir: /tmp

    - name: Start the application
      ansible.builtin.shell: ./start.sh
      args:
        chdir: {{ playbook_dir }}

    - name: Stop the application
      ansible.builtin.shell: ./stop.sh
      args:
        chdir: {{ playbook_dir }}
