### if the setting is applicable for all hosts in group then only update at group level 
#else updated at host level as shown in the sample file line no 2

[web]
192.168.64.41 git_repo='https://github.com/navneet-rathi/git-sample.git' start_path='./start.sh' stop_path='./stop.sh' repo_dir=/tmp/git-sample/ 
[app]
app1
app2
app3

[web:vars]
git_repo='https://github.com/navneet-rathi/git-sample.git'
start_path='./start.sh'
stop_path='./stop.sh'
repo_dir=/tmp/git-sample/
## We can keep it here as well but they will be visible recommended to keep them in vars.yml file and encrypt it using ansible-vault
#az_username=azureuser
#az_pat=ghp_1g0k5Z7J6r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8
[app:vars]
git_repo='https://github.com/navneet-rathi/git-sample.git'
start_path='./start.sh'
stop_path='./stop.sh'
repo_dir=/tmp/git-sample/
## We can keep it here as well but they will be visible recommended to keep them in vars.yml file and encrypt it using ansible-vault
#az_username=azureuser
#az_pat=ghp_1g0k5Z7J6r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8
